the brown table is bigger than the metal chair . 
the brown table is smaller than the metal chair . 
the brown table is bigger than the metal chair . 
the brown table is smaller than the metal chair . 
the brown table is bigger than the metal chair . 
the brown table is smaller than the metal chair . 
the brown table is bigger than the metal chair . 
the brown table is smaller than the metal chair . 
the metal chair is bigger than the brown table . 
the metal chair is smaller than the brown table . 
the metal chair is bigger than the brown table . 
the metal chair is smaller than the brown table . 
the metal chair is bigger than the brown table . 
the metal chair is smaller than the brown table . 
the metal chair is bigger than the brown table . 
the metal chair is smaller than the brown table . 
the girl is taller than the old woman . 
the girl is shorter than the old woman . 
the girl is taller than the old woman . 
the girl is shorter than the old woman . 
the girl is taller than the old woman . 
the girl is shorter than the old woman . 
the girl is taller than the old woman . 
the girl is shorter than the old woman . 
the girl is more cheerful than the old woman . 
the girl is less cheerful than the old woman . 
the girl is more cheerful than the old woman . 
the girl is less cheerful than the old woman . 
the girl is more cheerful than the old woman . 
the girl is less cheerful than the old woman . 
the girl is more cheerful than the old woman . 
the girl is less cheerful than the old woman . 
the old woman is taller than the girl . 
the old woman is shorter than the girl . 
the old woman is taller than the girl . 
the old woman is shorter than the girl . 
the old woman is taller than the girl . 
the old woman is shorter than the girl . 
the old woman is taller than the girl . 
the old woman is shorter than the girl . 
the old woman is more cheerful than the girl . 
the old woman is less cheerful than the girl . 
the old woman is more cheerful than the girl . 
the old woman is less cheerful than the girl . 
the old woman is more cheerful than the girl . 
the old woman is less cheerful than the girl . 
the old woman is more cheerful than the girl . 
the old woman is less cheerful than the girl . 